export const FETCH_HIMALAYA_REQUEST = "FETCH_HIMALAYA_REQUEST";
export const FETCH_HIMALAYA_SUCCESS = "FETCH_HIMALAYA_SUCCESS";
export const FETCH_HIMALAYA_FAILIURE = "FETCH_HIMALAYA_FAILURE";

export const FETCH_MAMAEARTH_REQUEST = "FETCH_MAMAEARTH_REQUEST";
export const FETCH_MAMAEARTH_SUCCESS = "FETCH_MAMAEARTH_SUCCESS";
export const FETCH_MAMAEARTH_FAILIURE = "FETCH_MAMAEARTH_FAILURE";

export const FETCH_CATEGORY_PRODUCTS_REQUEST = "FETCH_CATEGORY_PRODUCTS_REQUEST";
export const FETCH_CATEGORY_PRODUCTS_SUCCESS = "FETCH_CATEGORY_PRODUCTS_SUCCESS";
export const FETCH_CATEGORY_PRODUCTS_FAILURE = "FETCH_CATEGORY_PRODUCTS_FAILURE";
