export const Texts = {
    "OUR_STORY":"OUR STORY",
    "OUR_ROOTS":"OUR ROOTS",
    "OUR_PROCESS": "OUR PROCESS",
    'OUR_SCIENCE': 'OUR SCIENCE',
    'OUR_INITIATIVES': 'OUR INITIATIVES',
    "FOUNDED": 'Founded in 1930, Himalaya remains family owned withproducts offered in over 100 countries.',
    'INFO': 'Info',
    'CONTACT': 'Contact US',
    'FAQ':'FAQ',
    'BLOG': 'Blog',
    'STORE': 'Store Locator',
    'CAREERS': 'Careers',
    'POLICIES':'Policies',
    'SHIPPING_RETURNS': 'Shipping & Returns',
    'TERMS': 'Terms & Condition',
    'ACCESSIBILITY': 'Accessibility',
    'CONTACT_COMPANY':'Contact',
    'E_ADDRESS': 'writeous@himalayausa.com',
    'PHONE': 'Phone:',
    'M_NUMBER':'9012345678',
    'MAIL': 'Mail:',
    'HIMALAYA_WELLNESS': 'Himalaya Wellness',
    'HIMALAYA_ADDRESS': '1101 Gillingham lane Sugar Land, TX 77478',
    'SUBSCRIE': 'Subscribe',
    'AGREE_TERMS':'By entering yout email you agree to our terms & condition and Privacy Policy.',
    'FOLLOW': 'Follow Us:',
    'ASHWAGANDHA': 'ASHWAGANDHA',
    'STAR':'A star performer for stress and energy in a potent, organic caplet.',
    'UBTAN':'UBTAN',
    'ABOUT_UBTAN': 'Explore 100% toxin-free and safe Ubtan Range for Tan Removal and Radiant Skin, formulated with the goodness of natural ingredients and no harmful chemicals.',
    'WISDOM': 'Unlock the Wisdom of Herbs with Herbal Supplements, Toothpaste & More!',
    'FREE': 'Free',
    'PROMO': '**Promocode',
    'USE_CODE_HIMALAYA':'Use Code HIMALAYA20 to get 20% discount on himalaya products',
    'USE_CODE_REDEEM':'Use Code REDEEM20 to get 20% discount on mamaearth products',
    'USE_CODE_BODY':'Use Code BODY25 to get 25% discount on on mamaearth products',
    'ABOVE_35':'ON ALL ORDERS OVER ₹350',
    'PROMO_STAR': '**',
    'HERBAL_SUPPLEMENTS': 'Herbal Supplements',
    'SINGLE_HERBS': 'Single Herbs Supplements',
    'MULTI_SUPPLEMENTS': 'Multi-Ingredient Supplements',
    'ORAL_CARE': 'Oral Care',
    'ADULT_TOOTHPASTE': 'Adult Toothpaste',
    'KIDS_TOOTHPASTE': 'Kids Toothpaste',
    'PERSONAL_CARE': 'Personal Care',
    'FACE_CARE': 'Face Care',
    'CLEASING_CARE': 'Cleansing Bars',
    'BALM': 'Balm',
    'FEATURED_PRODUCTS': 'Featured Product',
    'FIND_OUT_WHY': 'Find out why everyone loves bestselling Organic Ashwagandha',
    'ABOUT': 'About',
    'SHOP': 'Shop',
    'LOOKING_FOR': 'What are you Looking for?',
    'REGISTER': 'Register',
    'CHECKOUT': 'CheckOut',
    'SHOPPING_CART': 'Shopping Cart',
    'TOTAL': 'Total',
    'PROCEED_CHECKOUT': 'PROCEED TO CHECKOUT',
    'VIEW_CART': 'View Cart',
    'PAYMENT_SUCCESSFULL': 'Payment Successfull',
    'YOUR_ORDER': 'Your Order of ',
    'IS_PLACED': 'is Placed ',
    'GO_TO_ORDER': 'Go To My Order',
    'ORDER_ID': 'Order ID',
    'PAYMENT_REF': 'Payment Ref. Number',
    'ORDER_DETAILS': 'Order Details',
    'ORDER_DATE': 'Order Date & Time',
    'MODE_PAYMENT': 'Mode of Payment',
    'ONLINE': 'Online',
    'CONTINUE_SHOPPING': '＜ Continue Shopping',
    'CLEAR_CART': 'Clear Shopping Cart',
    'SUBTOTAL': 'Subtotal',
    'GRAND_TOTAL': 'Grand Total: ₹ ',
    'YOU_MAY_BE_INTERESTED': 'You May Be Interested in These Products',
    'APPLY': 'Apply',
    'SHIPPING': 'Shipping',
    'DISCOUNT': 'Discount',
    'INFORMATION': 'Information',
    'PAYMENT': 'Payment',
    'CHANGE': 'Change',
    'SHIP_TO':'Ship to',
    'METHOD': 'Method',
    'STANDARD_FREE': 'Standard · Free',
    'STANDARD':'Standard',
    'ALL_TRANSACTIONS': 'All transactions are secure and encrypted.',
    'CREDIT_CARDS':'Credit Cards',
    'CREDIT_DETAILS': 'Credit Card Details',
    'AMAZON_LOGIN': 'You will be asked to login with Amazon.',
    'BILLING_ADDRESS': 'Billing address',
    'SELECT_ADDRESS': 'Select the address that matches your card or payment method',
    'SHIPPING_ADDRESS':'Same as shipping address',
    'DIFFERENT_ADDRESS':'Use a different billing address',
    'FEATURED':'Featured',
    'BEST_SELLING':'Best Selling',
    'N_ASC':'Name Ascending',
    'N_DSC':'Name Descending',
    'P_ASC':'Price Ascending',
    'P_DSC':'Price Descending',
    'CONTACT_INFORMATION': 'Contact information',
    'ALREADY_LOGIN':'Already have an account? Log in',
    'Shipping address': 'Shipping address',
    'UNITED_STATES':'United States',
    'STATE':'State',
    'SAVE_INFORMATION':' Save this information for next time',
    'GET_ORDER_UPDATE':'Get Order Updates On WhatsApp',
    'RETURN_TO_CART':'Return to Cart',
    'CONTINUE_SHIPPING':'Continue to shipping',
    'REFUND_POLICY':'Refund policy',
    'SHIPPING_POLICY':'Shipping policy',
    'PRIVACY_POLICY': 'Privacy policy',
    'TERMS_OF_SERVICE':'Terms of service',
    'ALREADY_REGISTERED':'Already Registered',
    'LOGIN':'Login',
    'LOGIN_WITH_GOOGLE':'Login With Google',
    'EMAIL':'E-mail',
    'REQUIRED_FIELDS':'Required Fields',
    'PASSWORD':'Password',
    'FORGOT_PASSWORD':'Forgot your password?',
    'NEW_CUSTOMER':'New Customer',
    'CREATE_ACCOUNT':'CREATE AN ACCOUNT',
    'HUMBLE_BEGINING': 'From Humble Beginnings',
    'LEGACY':'The Himalaya Legacy Now Spans Over 90 Years',
    'PURITY_EFFICIENCY': 'Purity and Efficacy',
    'PERSONAL_INFORMATION': 'Personal Information',
    'FIRST_NAME':'First Name',
    'CONFIRM_PASSWORD':'Confirm Password',
    'CREATE':'Create',
    'OR_RETURN': 'or Return To Store',
    'RETURN_INFORMATION':'Return to Information',
    'CONTINUE_TO_PAYMENT':'Continue to Payment',
    'HIMALAYA':'Himalaya',
    'MAMAEARTH': 'Mamaearth',
    'BODY':'Body',
    'BABY':'Baby',
    'MAKEUP':'Makeup',
    'HAIR_OIL':'Hair Oil',
    'FACE_CREAM':'Face Cream',
    'LIPSTICK':'Lipstick',
    'HALDI_UPTAN':'Haldi Uptan',
    'BODY_WASH':'Body Wash',
    'PERFUME':'Perfume',
    'HOME': 'Home'
}


export const PARAGRAPH = {
    'BEGINING': 'While riding through the forests of Burma, our founder, Mr. M. Manal, saw a villager pacify a restless elephant by feeding it the root of the plant Rauwolfia serpentina. Fascinated by the plant effect on the elephant, he returned home to India to seek scientific evidence for why this particular plant would have such a beneficial, calming effect. Young Manal mother gave him her bangles to sell so he could pursue his work, and Himalaya was born. Once he fully understood the science behind this special botanical, Mr. Manal bought a hand-operated, tablet-compressing machine and began his work. At night, his shoulders would ache from producing a few hundred tablets, one small tablet at a time. But his hard work paid off. This remarkable plant would later become Serpina, the world’s first anti-hypertensive drug in 1934. We remain in awe of the man who began our company, and the grandfather of our current CEO, Nabeel Manal. Himalaya’s legacy has always been one of researching nature and using the tools of modern science to develop and produce Ayurveda-based, pharmaceutical-grade herbal medicine products. And today, that legacy continues. Mr. Manal had a vision of helping people be well. Today, Himalaya Herbal Healthcare has turned a time-honored herbal tradition into a complete range of contemporary, proprietary formulas and single herbs dedicated to making the world well one person at a time.',
    'BILLING': 'Your order has been placed successfully. We will confirm the order in a few minutes.',
    'KEEP_ME_UPTODATE':'Keep me up to date on news and exclusive offers',
    'SINCE': 'Since 1930, Himalaya has been passionate about the healing wisdom of herbs. We offer a wide range of clinically- studied herbal supplements, toothpaste and personal care products that unlock the powerful healing benefits of herbs.',
    'BY_CREATING_ACCOUNT':'By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.',
    'BIODIVERSITY':'Biodiversity Conservation for Sustainable Living',
    'OUR_PROCESS':'The complexity and timing of the entire seed-to-shelf process for Himalaya and for the plants themselves, is highlighted by three important mandates: purity, efficacy, and batch-to-batch consistency. We know the success of traditional plant medicine is based on several integral parts that extend from the most advanced agricultural research and practices, to extraction methodologies, to formulating approaches and dosage strategies. To accomplish all of this, Himalaya maintains total control over the farming, harvesting, research, manufacturing, and distribution of all our products.',
    'COMMITMENT':'Commitment to Farmers',
    'HERBS_GROWN':' Himalaya herbs are grown on over 1,000 acres of farmland through fair trade, farming partnerships. Herbs are also sustainably wildcrafted on over 5,000 acres. Farms are located in regions most suitable to the individual herb so that the best possible quality and potency are achieved in the harvest. Just as one wine grape has more character and flavor when grown in a very specific region, the plants used in healthcare often perform best when they’re grown and harvested in their own unique native soil.',
    'OUR_ROOTS':' The herbs used in Himalaya Herbal Healthcare scientific product line are also used in the world oldest traditional system of medicine, Ayurveda, which dates back over 4,000 years. The word Ayurveda comes from the Sanskrit root words ayur, meaning “life” and veda, meaning “to know.” Ayurveda literally means "to know life,” or in the language of today, “the science of life.” Ayurveda had a profound, far-reaching influence on Traditional Chinese Medicine and the healthcare systems of many other countries and cultures that followed. Today, thanks to the dedicated efforts of Himalaya’s doctors and scientists, it been proven effective through scientific validation. Ayurveda acknowledges there are five elements that make up the universe and the human body; earth, water fire, air and space. It seeks to bring the constellation and characteristics of the three body types defined by those elements – the vata, pitta and kapha – back into balance through proper diet, herbal treatment, and emotional well-being.',
    'OUR_STORY':'Founded in 1930, the Himalaya legacy now spans over 90 years, stretching from one man, to his son, to his grandson. From our humble beginnings in India, our products are now offered in over 100 countries, yet we’re still family owned. Himalaya offers a full line of clinically-studied herbal formulations, certified USDA organic Single herbs, and a full line of body care products. Integrating the principles of traditional medicine with modern science, Himalaya is a worldwide pioneer in the field of scientifically validated herbal healthcare. Himalaya North American LEED® Gold-Certified eco-friendly corporate office and warehouse facility are located in Sugar Land, Texas, a community neighboring Houston.',
    'OUR_FARMS': 'Our Farms',
}
